groundupnews/gu

requirements.txt

Memcache fix after Django 4.2.5 update

replace python-memcached with pymemcache

---

newsroom/forms.py
newsroom/templates/newsroom/article_list_form.html
newsroom/views.py

Updated article form to use date field

---

newsroom/templates/newsroom/article_block.html

payfast donation button in articles

---

gallery/views.py

#47 
Passes all tests; last page now works properly thanks to a simple check :)

fix gallery pagination -- last page

---

newsroom/views.py
templates/search/search.html

#54 
Fixed by adding context to the search for the gallery.
Passes all tests!

added gallery context to search to maintain search type

---

gallery/models.py
gallery/views.py

Featured photo order

---

newsroom/forms.py
newsroom/views.py

#50 
Fixed by adding validation and sanitation to the author parameter, which is needed as an integer.

fix error 500 - author param lacked validation // sanitation

---

newsroom/views.py
templates/paginator.html

#79 
Added all the parameters to additional_parameters, so search context now persists

fix advanced search context missing some parameters

---

groundup/settings.py
groundup/urls.py
judgment/tests.py
templates/menu.html

disabled the judgment app by commenting it in settings & urls
@nathangeffen @groundupnews please make a basic flatpage on .org.za for users to know
passes all tests & addresses #73

disable judgment app until further notice

---

newsroom/views.py

Fixes bug with advanced search additional parameters

Try/except the additional_parameters logic temporarily

---

agony/feeds.py
agony/templates/agony/qanda_list.html
agony/urls.py

#70 
Implemented an RSS feed for Q&A as requested.
Includes short answer + full answer, as well as a link to the page.
Please do thorough testing @groundupnews @nathangeffen

Q&A RSS Feed implementation

---

agony/tests.py
analyzer/tests.py
blocks/tests.py
gallery/tests.py
newsroom/tests.py
pgsearch/tests.py
security/tests.py
socialmedia/tests.py

Addresses issue #84 
New/improved test cases for: agony, analyzer, blocks, gallery, newsroom, pgsearch, security, and socialmedia.
This brings the total to 42.

Expanded the test cases for numerous apps

---

agony/feeds.py
agony/templates/agony/qanda_list.html

Addresses #94 - added a disclaimer to the agony page.

Add Agony Disclaimer

---

agony/feeds.py
agony/urls.py

Reenable RSS feed for Agony

---

gallery/settings.py

Addresses & closes #92
Date updated to 2016-2025

Update copyright date on Gallery

---

gallery/templates/gallery/photo_detail.html

Closes #90
@nathangeffen Please test on your side to make sure the host is copied. Logic checks out, but locally obviously gives me 127.0.0.1:8000 and not groundup.org.za so just want to make sure.

Copy image buttons in gallery

---

agony/templates/agony/qanda_list.html

Closes #103 
A very silly mistake indeed!

Add missing italics closing tag

---

agony/templates/agony/response.html

Added the disclaimer for agony aunt to the email responses. 
Addresses & closes #110 
Tested, and works and scales as it should.

Disclaimer in email responses

---

newsroom/templates/newsroom/article_detail.html

Add indicator if region is missing

---

letters/templates/letters/rejected_letter.html

Addresses & closes #96 
Letter text now present in rejection emails.

Add letter text to rejection emails

---

agony/templates/agony/qanda_detail.html

Addresses & closes #118 
New:
Before:

Expand & move Q&A disclaimer

---

gallery/templates/gallery/photo_detail.html
gallery/templates/gallery/photo_download.html
gallery/urls.py
gallery/views.py

Request from #57 - 
> When downloading go to separate page/popup that includes:
> - Thank you + donate to groundup
> - explain editorial usage and creative commons
_PR adds a dedicated download thanks page for photos, with info on copyright, attribution, and licensing, and updates the routing and views to support these changes._ 
**Preview:**

Gallery Rework - Download Thanks Page
